### ISSUE TITLE
大量获取历史数据时出现连接失败的情况。

### ISSUE THREAD

**Issue by caoyu-yiyue** [dd-center/vtbs.moe#130]
使用 https://api.vtbs.moe/v1/info 获取到所有的mid，然后按照mid 获取所有的历史信息，今天开始就会不停出现断连的情况，以前都没有过，网络环境什么的也没变。比如使用异步时会出现如下的问题：

```python
import requests
import pandas as pd
import asyncio
from aiohttp import ClientSession

vtb_info: requests.Response = requests.get('https://api.vtbs.moe/v1/info')
info_df: pd.DataFrame = pd.DataFrame.from_dict(vtb_info.json()).set_index('mid')
mid_list = vtb_name.index.tolist()

async def get_vtb_history(url, session, mid):
    async with session.get(url) as response:
        response_json = await response.json()
        one_df = pd.DataFrame.from_dict(response_json)
        one_df['mid'] = mid
        return one_df


async def arun(mid_list):
    url = 'https://api.vtbs.moe/v2/bulkActive/{}'
    tasks = []

    async with ClientSession() as session:
        for mid in mid_list:
            task = asyncio.ensure_future(
                get_vtb_history(url.format(mid), session, mid))
            tasks.append(task)

        responses = await asyncio.gather(*tasks)
        return responses

loop = asyncio.get_event_loop()
future = asyncio.ensure_future(arun(mid_list))
vtd_his_list = loop.run_until_complete(future)
```

会出现下面的错误：

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 981, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1009, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<stdin>", line 9, in arun
  File "<stdin>", line 2, in get_vtb_history
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.vtbs.moe:443 ssl:default [None]
```

不使用异步的话这里也会跑着跑着突然卡住
```
all_dfs = []
    for mid in mid_list:
        print(mid)
        his_data_response: requests.Response = requests.get(
            'https://api.vtbs.moe/v2/bulkActive/{}'.format(mid))
        his_resp_json = his_data_response.json()
        one_df = pd.DataFrame.from_dict(his_resp_json)
        one_df['mid'] = mid
        all_dfs.append(one_df)
```

会报如下的错误：

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tokyo.vtbs.moe', port=443): Max retries exceeded with url: /v2/bulkActive/147529 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.tokyo.vtbs.moe', port=443): Max retries exceeded with url: /v2/bulkActive/147529 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))
```

几天前还都没问题，至少1 月4 号的时候还能正常请求数据，今天（1月7日）上午开始就一直都不行了。自己只会一点数据处理，对后端也不太了解，不知道是发生了什么问题呢。

**Comment by simon300000** [comment]
试一下把域名替换成 api.tokyo.vtbs.moe 看看？这是直接连东京的服务器，跳过cdn

**Comment by simon300000** [comment]
我在这段时间没有更改什么设置，所以我也不是很清楚怎么回事（

**Comment by simon300000** [comment]
可以直接进行重试吗

**Comment by caoyu-yiyue** [comment]
我试试找个其他网络再试一下。刚刚查了似乎aiohttp 没有直接重试的设置……
另外有可能设置一个借口直接获得所有mid 的历史数据吗，这样是不是只需要连接一次对网络要求低一点。

**Comment by caoyu-yiyue** [comment]
现在用东京这个地址也还是有一样的问题，如果最近没动过什么设置的话我也有点怀疑是我的网络出了什么问题了……

**Comment by simon300000** [comment]
做一个接口直接返回所有数据的按照一定格式拼起来变成一个二进制的样子吧→_→
希望可以解决这个问题www

**Comment by caoyu-yiyue** [comment]
今天换了一个网络发现真的是网络问题……🤦🏻‍♂️好尴尬啊，我自闭了🤦🏻‍♂️

**Comment by simon300000** [comment]
哈哈 能解决那就好
过两天我把那个二进制api做出来之后大概可以减少请求，应该能好很多→_→

**Comment by caoyu-yiyue** [comment]
OK，感谢！有统一请求所有数据的 API 再好不过啦！我也不用担心频繁请求给服务器造成太多负担（话说今天刚因为请求过多被 BiliOB 给禁止访问了😅🤦🏻‍♂️）

**Comment by simon300000** [comment]
加入了一个可以请求所有数据的API
https://github.com/dd-center/vtbs.moe#all-active-httpsapivtbsmoev3allactive

**Comment by caoyu-yiyue** [comment]
感谢感谢！辛苦啦！

**Comment by simon300000** [comment]
嘿嘿 应该解决了吧

**Comment by caoyu-yiyue** [comment]
后来又一直不间断地遇到同样的问题，今天终于调查清原因了。当初以为是网络问题，但实际上是：我自行设定了 proxy 环境变量，但 aiohttp 默认不支持连接到 proxy，需要在创建 ClientSession 对象时设定参数 trust_env = True.

所以将如上代码的 arun 函数更改为以下形式即可解决：

```Python
async def arun(mid_list):
    url = 'https://api.vtbs.moe/v2/bulkActive/{}'
    tasks = []

    async with ClientSession(trust_env=True) as session:
        for mid in mid_list:
            task = asyncio.ensure_future(
                get_vtb_history(url.format(mid), session, mid))
            tasks.append(task)

        responses = await asyncio.gather(*tasks)
        return responses
```

如果有使用 aiohttp 遇到相同问题的各位，希望能帮到大家。
