### ISSUE TITLE
奇怪的BUG

### ISSUE THREAD

**Issue by simon300000** [dd-center/vtbs.moe#400]
```
Error: Target route: mid -> oneOf: [getInfoByRoom -> roomid -> liveRoom -> info -> mid -> LOOP, view -> bvid -> archiveStat -> aid -> aid -> LOOP, search -> uname -> info -> mid -> LOOP]
    at RelationX.relation (/data/p/v/vtbs.moe/node_modules/relationx/src/index.js:7:23)
    at module.exports (/data/p/v/vtbs.moe/node_modules/bili-api/src/index.js:33:88)
    at race (file:///data/p/v/vtbs.moe/api/interface/biliapi.js:6:85)
    at coreFetch (file:///data/p/v/vtbs.moe/api/spider.js:45:24)
    at file:///data/p/v/vtbs.moe/api/spider.js:60:24
    at file:///data/p/v/vtbs.moe/api/spider.js:203:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///data/p/v/vtbs.moe/api/spider.js:201:24
    at async file:///data/p/v/vtbs.moe/api/spider.js:201:24
    at async file:///data/p/v/vtbs.moe/api/spider.js:201:24
```

**Comment by simon300000** [comment]
这个是因为部分mid为undefined
