### ISSUE TITLE
解决hawk会不定时奔溃的问题

### ISSUE THREAD

**Issue by simon300000** [dd-center/vtbs.moe#72]
6|api.vtbs | TypeError: Cannot convert object to primitive value
6|api.vtbs |     at Array.join (<anonymous>)
6|api.vtbs |     at Timeout._onTimeout (/var/www/vtbs.moe/hawk/index.js:60:36)
6|api.vtbs |     at listOnTimeout (internal/timers.js:531:17)
6|api.vtbs |     at processTimers (internal/timers.js:475:7)

**Comment by simon300000** [comment]
可能是nodejs的问题

**Comment by simon300000** [comment]
升级了nodejs之后似乎不会发生了
